import java.sql.Connection;
import javax.swing.JFrame;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Safiyyah Yahya
 */
public class Login extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        koneksi();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    public Connection connection;
    public Statement statement;
    public PreparedStatement pstm;
    public ResultSet rs = null;
    
    public void koneksi(){
        if(connection == null){
            try{
                String url = "jdbc:mysql://localhost:3306/serbatopup";                
                Class.forName("com.mysql.cj.jdbc.Driver");
                connection = DriverManager.getConnection(url, "root", "");
                java.sql.Statement st = connection.createStatement();
                //JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
            } catch(ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Koneksi Gagal");
                e.printStackTrace();
            }
        }        
    }
    
    public void setKosong(){
        tf_Username.setText("");
        tf_Password.setText("");
    }
    
    private boolean cekUsernameTerdaftar(String username) {
        try {
            String sql = "SELECT * FROM register WHERE username = ?";
            pstm = connection.prepareStatement(sql);
            pstm.setString(1, username);
            ResultSet r = pstm.executeQuery();
            return r.next();
        } catch (SQLException e) {
            return true;
        }
    }
    
    private boolean cekPasswordTerdaftar(String password) {
        try {
            String sql = "SELECT * FROM register WHERE password = ?";
            pstm = connection.prepareStatement(sql);
            pstm.setString(1, password);
            ResultSet r = pstm.executeQuery();
            return r.next();
        } catch (SQLException e) {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        txt_Login = new javax.swing.JLabel();
        txt_Username = new javax.swing.JLabel();
        tf_Username = new javax.swing.JTextField();
        txt_Password = new javax.swing.JLabel();
        tf_Password = new javax.swing.JPasswordField();
        check_ShowPassword = new javax.swing.JCheckBox();
        btn_Login = new javax.swing.JButton();
        txt_DontReadyAcc = new javax.swing.JLabel();
        txt_RegisterHere = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(204, 204, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(722, 615));
        mainPanel.setMinimumSize(new java.awt.Dimension(722, 615));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(153, 153, 255));
        panelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Login.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Login.setText("L O G I N");
        panelLogin.add(txt_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, -1));

        txt_Username.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        txt_Username.setText("Username");
        panelLogin.add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        tf_Username.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        tf_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_UsernameActionPerformed(evt);
            }
        });
        panelLogin.add(tf_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 340, 40));

        txt_Password.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        txt_Password.setText("Password");
        panelLogin.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        tf_Password.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        panelLogin.add(tf_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 340, 40));

        check_ShowPassword.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        check_ShowPassword.setText(" Show Password");
        check_ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_ShowPasswordActionPerformed(evt);
            }
        });
        panelLogin.add(check_ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 359, -1, 30));

        btn_Login.setBackground(new java.awt.Color(204, 204, 255));
        btn_Login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Login.setText("LOGIN");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        panelLogin.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 150, -1));

        mainPanel.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 380, 460));

        txt_DontReadyAcc.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        txt_DontReadyAcc.setText("Don't have an account?");
        mainPanel.add(txt_DontReadyAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, -1, -1));

        txt_RegisterHere.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        txt_RegisterHere.setText("Register Here");
        txt_RegisterHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_RegisterHereMouseClicked(evt);
            }
        });
        mainPanel.add(txt_RegisterHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_UsernameActionPerformed

    private void check_ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_ShowPasswordActionPerformed
        if(check_ShowPassword.isSelected()){
            tf_Password.setEchoChar((char)0);
        }else{
            tf_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_check_ShowPasswordActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        String username_user, password, query;
        String url = "jdbc:mysql://localhost:3306/serbatopup";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection(url, "root", "");
            java.sql.Statement st = con.createStatement();

            if (this.tf_Username.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Username belum diisi", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
            } else if (!(cekUsernameTerdaftar(tf_Username.getText()))) {
                JOptionPane.showMessageDialog(this, "Username yang kamu masukkan belum terdaftar", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
            } else if (new String(tf_Password.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(null, "Password belum diisi", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
            } else if(!(cekPasswordTerdaftar(new String(tf_Password.getPassword())))) {
                JOptionPane.showMessageDialog(this, "Password yang kamu masukkan tidak sesuai", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
            } else {
                username_user = tf_Username.getText();
                password = new String(tf_Password.getPassword());
                query = "INSERT INTO login(username, password) VALUES('" + username_user + "','" + password + "')";
                st.execute(query);
                JOptionPane.showMessageDialog(null, "Halo, " + tf_Username.getText(), "Pesan Informasi", JOptionPane.INFORMATION_MESSAGE);
                setKosong();
                MenuUtamaTopUp menuUtamaTopUp = new MenuUtamaTopUp();
                menuUtamaTopUp.setVisible(true);
            this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal!", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void txt_RegisterHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_RegisterHereMouseClicked
        Register register = new Register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txt_RegisterHereMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JCheckBox check_ShowPassword;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField tf_Password;
    private javax.swing.JTextField tf_Username;
    private javax.swing.JLabel txt_DontReadyAcc;
    private javax.swing.JLabel txt_Login;
    private javax.swing.JLabel txt_Password;
    private javax.swing.JLabel txt_RegisterHere;
    private javax.swing.JLabel txt_Username;
    // End of variables declaration//GEN-END:variables
}
