/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Safiyyah Yahya 
 */
public class MenuUtamaTopUp extends javax.swing.JFrame {
    
    String tipe = "", status = "", cekMetodePembayaran = "", pembayaran = "", pesanan = "";
    double diskon = 0;
    int nominalDiskon = 0, harga = 0,  total = 0;
    
    public Connection connection;
    public Statement statement;
    public PreparedStatement pstm;
    public ResultSet rs = null;
    /**
     * Creates new form Home
     */
    public MenuUtamaTopUp() {
        initComponents();
        koneksi();
        cekMetodePembayaran = "Bank";
        pesanan = "PULSA";
        tipe = "Tri";
        jLPilihPulsa.setVisible(true);
        jLPilihEMoney.setVisible(false);
        jLPilihGame.setVisible(false);
        jLGerai.setVisible(false);
        this.setLocationRelativeTo(null);
        metodePembayaran.setLocationRelativeTo(null);
        konfirmasiPembayaran.setLocationRelativeTo(null);
    }
    
    public void koneksi(){
        if(connection == null){
            try{
                String url = "jdbc:mysql://localhost:3306/serbatopup";                
                Class.forName("com.mysql.cj.jdbc.Driver");
                connection = DriverManager.getConnection(url, "root", "");
                java.sql.Statement st = connection.createStatement();
                //JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
            } catch(ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Koneksi Gagal");
                e.printStackTrace();
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        konfirmasiPembayaran = new javax.swing.JFrame();
        panelKp = new javax.swing.JPanel();
        txt_kodePembayaran = new javax.swing.JLabel();
        txt_metodePembayaran = new javax.swing.JLabel();
        panel_kode = new javax.swing.JPanel();
        kode = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        metodePembayaran = new javax.swing.JFrame();
        panelMp = new javax.swing.JPanel();
        txt_pilihMp = new javax.swing.JLabel();
        cb_metodePembayaran = new javax.swing.JComboBox<>();
        jLTransferBank = new javax.swing.JLayeredPane();
        bca = new javax.swing.JRadioButton();
        mandiri = new javax.swing.JRadioButton();
        bni = new javax.swing.JRadioButton();
        bri = new javax.swing.JRadioButton();
        jLGerai = new javax.swing.JLayeredPane();
        alfamart = new javax.swing.JRadioButton();
        indomaret = new javax.swing.JRadioButton();
        kantorPos = new javax.swing.JRadioButton();
        bnt_bayar = new javax.swing.JButton();
        btGroup_MP = new javax.swing.ButtonGroup();
        panelUtama = new javax.swing.JPanel();
        txt_serbaTopUp = new javax.swing.JLabel();
        txt_noHp = new javax.swing.JLabel();
        cb_jenisTopUp = new javax.swing.JComboBox<>();
        txt_topUpApa = new javax.swing.JLabel();
        tf_noHp = new javax.swing.JTextField();
        tf_Nama = new javax.swing.JTextField();
        jLPilihPulsa = new javax.swing.JLayeredPane();
        panel_provider = new javax.swing.JPanel();
        btn_Tri = new javax.swing.JButton();
        btn_Telkomsel = new javax.swing.JButton();
        btn_Indosat = new javax.swing.JButton();
        btn_Xl = new javax.swing.JButton();
        jLPilihEMoney = new javax.swing.JLayeredPane();
        panelEMoney = new javax.swing.JPanel();
        btn_dana = new javax.swing.JButton();
        btn_GoPay = new javax.swing.JButton();
        btn_ShopeePay = new javax.swing.JButton();
        btn_Ovo = new javax.swing.JButton();
        jLPilihGame = new javax.swing.JLayeredPane();
        panelGame = new javax.swing.JPanel();
        btn_ML = new javax.swing.JButton();
        btn_PUBG = new javax.swing.JButton();
        btn_Genshin = new javax.swing.JButton();
        btn_Punishing = new javax.swing.JButton();
        LP_Nominal = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();
        btnHargaA = new javax.swing.JButton();
        btnHargaB = new javax.swing.JButton();
        btnHargaC = new javax.swing.JButton();
        btnHargaD = new javax.swing.JButton();
        txt_total = new javax.swing.JLabel();
        txt_Nama = new javax.swing.JLabel();
        txt_PilihNominal = new javax.swing.JLabel();
        totalHarga = new javax.swing.JLabel();
        txt_diskon = new javax.swing.JLabel();
        diskonTotal = new javax.swing.JLabel();
        btn_transaksiTerakhir = new javax.swing.JButton();
        btn_pilihPembayaran = new javax.swing.JButton();
        btn_status = new javax.swing.JButton();
        txt_noHp1 = new javax.swing.JLabel();

        konfirmasiPembayaran.setMinimumSize(new java.awt.Dimension(379, 326));
        konfirmasiPembayaran.setResizable(false);
        konfirmasiPembayaran.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelKp.setBackground(new java.awt.Color(153, 153, 255));
        panelKp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_kodePembayaran.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_kodePembayaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_kodePembayaran.setText("Kode Pembayaran");
        panelKp.add(txt_kodePembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 359, -1));

        txt_metodePembayaran.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_metodePembayaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_metodePembayaran.setText("METODE PEMBAYARAN");
        panelKp.add(txt_metodePembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 359, -1));

        panel_kode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        kode.setBackground(new java.awt.Color(255, 255, 255));
        kode.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        kode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kode.setText("-");

        javax.swing.GroupLayout panel_kodeLayout = new javax.swing.GroupLayout(panel_kode);
        panel_kode.setLayout(panel_kodeLayout);
        panel_kodeLayout.setHorizontalGroup(
            panel_kodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kodeLayout.createSequentialGroup()
                .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_kodeLayout.setVerticalGroup(
            panel_kodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kode, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        panelKp.add(panel_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 137, -1, -1));

        btn_ok.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ok.setText("OK");
        btn_ok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        panelKp.add(btn_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 278, 33));

        konfirmasiPembayaran.getContentPane().add(panelKp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        metodePembayaran.setMinimumSize(new java.awt.Dimension(394, 320));
        metodePembayaran.setResizable(false);

        panelMp.setBackground(new java.awt.Color(153, 153, 255));
        panelMp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pilihMp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_pilihMp.setForeground(new java.awt.Color(255, 255, 255));
        txt_pilihMp.setText("Pilih Metode Pembayaran");
        panelMp.add(txt_pilihMp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cb_metodePembayaran.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        cb_metodePembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transfer Bank (VA Account)", "Gerai" }));
        cb_metodePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_metodePembayaranActionPerformed(evt);
            }
        });
        panelMp.add(cb_metodePembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 320, 30));

        jLTransferBank.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btGroup_MP.add(bca);
        bca.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        bca.setText("BCA");
        bca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaActionPerformed(evt);
            }
        });
        jLTransferBank.add(bca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        btGroup_MP.add(mandiri);
        mandiri.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        mandiri.setText("Mandiri");
        mandiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandiriActionPerformed(evt);
            }
        });
        jLTransferBank.add(mandiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        btGroup_MP.add(bni);
        bni.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        bni.setText("BNI");
        bni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bniActionPerformed(evt);
            }
        });
        jLTransferBank.add(bni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        btGroup_MP.add(bri);
        bri.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        bri.setText("BRI");
        bri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                briActionPerformed(evt);
            }
        });
        jLTransferBank.add(bri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        panelMp.add(jLTransferBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 320, 110));

        jLGerai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btGroup_MP.add(alfamart);
        alfamart.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        alfamart.setText("Alfamart");
        alfamart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfamartActionPerformed(evt);
            }
        });
        jLGerai.add(alfamart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        btGroup_MP.add(indomaret);
        indomaret.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        indomaret.setText("Indomaret");
        indomaret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indomaretActionPerformed(evt);
            }
        });
        jLGerai.add(indomaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, -1, -1));

        btGroup_MP.add(kantorPos);
        kantorPos.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        kantorPos.setText("Kantor Pos");
        kantorPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kantorPosActionPerformed(evt);
            }
        });
        jLGerai.add(kantorPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, -1, -1));

        panelMp.add(jLGerai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 320, 120));

        bnt_bayar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bnt_bayar.setText("BAYAR");
        bnt_bayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bnt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_bayarActionPerformed(evt);
            }
        });
        panelMp.add(bnt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 320, 30));

        javax.swing.GroupLayout metodePembayaranLayout = new javax.swing.GroupLayout(metodePembayaran.getContentPane());
        metodePembayaran.getContentPane().setLayout(metodePembayaranLayout);
        metodePembayaranLayout.setHorizontalGroup(
            metodePembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMp, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        metodePembayaranLayout.setVerticalGroup(
            metodePembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metodePembayaranLayout.createSequentialGroup()
                .addComponent(panelMp, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Top Up");
        setBackground(new java.awt.Color(51, 153, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUtama.setBackground(new java.awt.Color(153, 153, 255));
        panelUtama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_serbaTopUp.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txt_serbaTopUp.setText("SERBA TOP-UP");
        panelUtama.add(txt_serbaTopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        txt_noHp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_noHp.setText("NO HP");
        panelUtama.add(txt_noHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        cb_jenisTopUp.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cb_jenisTopUp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PULSA", "E-MONEY", "GAME" }));
        cb_jenisTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_jenisTopUpActionPerformed(evt);
            }
        });
        panelUtama.add(cb_jenisTopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 254, 40));

        txt_topUpApa.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txt_topUpApa.setText("TOP-UP APA");
        panelUtama.add(txt_topUpApa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        tf_noHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_noHpKeyTyped(evt);
            }
        });
        panelUtama.add(tf_noHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 140, -1));
        panelUtama.add(tf_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, -1));

        panel_provider.setBackground(new java.awt.Color(204, 204, 255));
        panel_provider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panel_provider.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Tri.setBackground(new java.awt.Color(102, 102, 255));
        btn_Tri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Tri.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tri.setText("Tri");
        btn_Tri.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_Tri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TriActionPerformed(evt);
            }
        });
        panel_provider.add(btn_Tri, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 40));

        btn_Telkomsel.setBackground(new java.awt.Color(102, 102, 255));
        btn_Telkomsel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Telkomsel.setForeground(new java.awt.Color(255, 255, 255));
        btn_Telkomsel.setText("Telkomsel");
        btn_Telkomsel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_Telkomsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TelkomselActionPerformed(evt);
            }
        });
        panel_provider.add(btn_Telkomsel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 150, 40));

        btn_Indosat.setBackground(new java.awt.Color(102, 102, 255));
        btn_Indosat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Indosat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Indosat.setText("Indosat");
        btn_Indosat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_Indosat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IndosatActionPerformed(evt);
            }
        });
        panel_provider.add(btn_Indosat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 150, 40));

        btn_Xl.setBackground(new java.awt.Color(102, 102, 255));
        btn_Xl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Xl.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xl.setText("XL");
        btn_Xl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_Xl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XlActionPerformed(evt);
            }
        });
        panel_provider.add(btn_Xl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 150, 40));

        jLPilihPulsa.setLayer(panel_provider, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLPilihPulsaLayout = new javax.swing.GroupLayout(jLPilihPulsa);
        jLPilihPulsa.setLayout(jLPilihPulsaLayout);
        jLPilihPulsaLayout.setHorizontalGroup(
            jLPilihPulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(jLPilihPulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_provider, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );
        jLPilihPulsaLayout.setVerticalGroup(
            jLPilihPulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jLPilihPulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_provider, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );

        panelUtama.add(jLPilihPulsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 410, 140));

        panelEMoney.setBackground(new java.awt.Color(204, 204, 255));
        panelEMoney.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelEMoney.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_dana.setBackground(new java.awt.Color(102, 102, 255));
        btn_dana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_dana.setForeground(new java.awt.Color(255, 255, 255));
        btn_dana.setText("DANA");
        btn_dana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_dana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_danaActionPerformed(evt);
            }
        });
        panelEMoney.add(btn_dana, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 40));

        btn_GoPay.setBackground(new java.awt.Color(102, 102, 255));
        btn_GoPay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_GoPay.setForeground(new java.awt.Color(255, 255, 255));
        btn_GoPay.setText("GO-PAY");
        btn_GoPay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_GoPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GoPayActionPerformed(evt);
            }
        });
        panelEMoney.add(btn_GoPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 150, 40));

        btn_ShopeePay.setBackground(new java.awt.Color(102, 102, 255));
        btn_ShopeePay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ShopeePay.setForeground(new java.awt.Color(255, 255, 255));
        btn_ShopeePay.setText("SHOPEE-PAY");
        btn_ShopeePay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_ShopeePay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShopeePayActionPerformed(evt);
            }
        });
        panelEMoney.add(btn_ShopeePay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 150, 40));

        btn_Ovo.setBackground(new java.awt.Color(102, 102, 255));
        btn_Ovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Ovo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ovo.setText("OVO");
        btn_Ovo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_Ovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OvoActionPerformed(evt);
            }
        });
        panelEMoney.add(btn_Ovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 150, 40));

        jLPilihEMoney.setLayer(panelEMoney, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLPilihEMoneyLayout = new javax.swing.GroupLayout(jLPilihEMoney);
        jLPilihEMoney.setLayout(jLPilihEMoneyLayout);
        jLPilihEMoneyLayout.setHorizontalGroup(
            jLPilihEMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(jLPilihEMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelEMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );
        jLPilihEMoneyLayout.setVerticalGroup(
            jLPilihEMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jLPilihEMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelEMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );

        panelUtama.add(jLPilihEMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 410, 140));

        panelGame.setBackground(new java.awt.Color(204, 204, 255));
        panelGame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ML.setBackground(new java.awt.Color(102, 102, 255));
        btn_ML.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ML.setForeground(new java.awt.Color(255, 255, 255));
        btn_ML.setText("Mobile Legends");
        btn_ML.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_ML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MLActionPerformed(evt);
            }
        });
        panelGame.add(btn_ML, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 40));

        btn_PUBG.setBackground(new java.awt.Color(102, 102, 255));
        btn_PUBG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_PUBG.setForeground(new java.awt.Color(255, 255, 255));
        btn_PUBG.setText("PUBG MOBILE");
        btn_PUBG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_PUBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PUBGActionPerformed(evt);
            }
        });
        panelGame.add(btn_PUBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 150, 40));

        btn_Genshin.setBackground(new java.awt.Color(102, 102, 255));
        btn_Genshin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Genshin.setForeground(new java.awt.Color(255, 255, 255));
        btn_Genshin.setText("GENSHIN IMPACT");
        btn_Genshin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_Genshin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenshinActionPerformed(evt);
            }
        });
        panelGame.add(btn_Genshin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 150, 40));

        btn_Punishing.setBackground(new java.awt.Color(102, 102, 255));
        btn_Punishing.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_Punishing.setForeground(new java.awt.Color(255, 255, 255));
        btn_Punishing.setText("PUNISHING GREY RAVEN");
        btn_Punishing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_Punishing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PunishingActionPerformed(evt);
            }
        });
        panelGame.add(btn_Punishing, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 150, 40));

        jLPilihGame.setLayer(panelGame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLPilihGameLayout = new javax.swing.GroupLayout(jLPilihGame);
        jLPilihGame.setLayout(jLPilihGameLayout);
        jLPilihGameLayout.setHorizontalGroup(
            jLPilihGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(jLPilihGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGame, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );
        jLPilihGameLayout.setVerticalGroup(
            jLPilihGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jLPilihGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGame, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );

        panelUtama.add(jLPilihGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 410, 140));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHargaA.setBackground(new java.awt.Color(102, 102, 255));
        btnHargaA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHargaA.setForeground(new java.awt.Color(255, 255, 255));
        btnHargaA.setText("Rp 10.000");
        btnHargaA.setBorder(null);
        btnHargaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaAActionPerformed(evt);
            }
        });
        jPanel5.add(btnHargaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 40));

        btnHargaB.setBackground(new java.awt.Color(102, 102, 255));
        btnHargaB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHargaB.setForeground(new java.awt.Color(255, 255, 255));
        btnHargaB.setText("Rp 25.000");
        btnHargaB.setBorder(null);
        btnHargaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaBActionPerformed(evt);
            }
        });
        jPanel5.add(btnHargaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 170, 40));

        btnHargaC.setBackground(new java.awt.Color(102, 102, 255));
        btnHargaC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHargaC.setForeground(new java.awt.Color(255, 255, 255));
        btnHargaC.setText("Rp 50.000");
        btnHargaC.setBorder(null);
        btnHargaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaCActionPerformed(evt);
            }
        });
        jPanel5.add(btnHargaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 40));

        btnHargaD.setBackground(new java.awt.Color(102, 102, 255));
        btnHargaD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHargaD.setForeground(new java.awt.Color(255, 255, 255));
        btnHargaD.setText("Rp 100.000");
        btnHargaD.setBorder(null);
        btnHargaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaDActionPerformed(evt);
            }
        });
        jPanel5.add(btnHargaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 170, 40));

        LP_Nominal.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LP_NominalLayout = new javax.swing.GroupLayout(LP_Nominal);
        LP_Nominal.setLayout(LP_NominalLayout);
        LP_NominalLayout.setHorizontalGroup(
            LP_NominalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(LP_NominalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );
        LP_NominalLayout.setVerticalGroup(
            LP_NominalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(LP_NominalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );

        panelUtama.add(LP_Nominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 410, 140));

        txt_total.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txt_total.setText("TOTAL      :");
        panelUtama.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        txt_Nama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Nama.setText("NAMA");
        panelUtama.add(txt_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txt_PilihNominal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txt_PilihNominal.setText("PILIH NOMINAL");
        panelUtama.add(txt_PilihNominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        totalHarga.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        totalHarga.setText("Rp 0.00");
        panelUtama.add(totalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 110, -1));

        txt_diskon.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txt_diskon.setText("DISKON   :");
        panelUtama.add(txt_diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        diskonTotal.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        diskonTotal.setText("Rp 0.00");
        panelUtama.add(diskonTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 110, -1));

        btn_transaksiTerakhir.setBackground(new java.awt.Color(102, 102, 255));
        btn_transaksiTerakhir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_transaksiTerakhir.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksiTerakhir.setText("TRANSAKSI TERAKHIR");
        btn_transaksiTerakhir.setBorder(null);
        btn_transaksiTerakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiTerakhirActionPerformed(evt);
            }
        });
        panelUtama.add(btn_transaksiTerakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 180, 30));

        btn_pilihPembayaran.setBackground(new java.awt.Color(102, 102, 255));
        btn_pilihPembayaran.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_pilihPembayaran.setForeground(new java.awt.Color(255, 255, 255));
        btn_pilihPembayaran.setText("PILIH PEMBAYARAN");
        btn_pilihPembayaran.setBorder(null);
        btn_pilihPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihPembayaranActionPerformed(evt);
            }
        });
        panelUtama.add(btn_pilihPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 180, 30));

        btn_status.setBackground(new java.awt.Color(102, 102, 255));
        btn_status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_status.setForeground(new java.awt.Color(255, 255, 255));
        btn_status.setText("STATUS");
        btn_status.setBorder(null);
        btn_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statusActionPerformed(evt);
            }
        });
        panelUtama.add(btn_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 180, 30));

        txt_noHp1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_noHp1.setText("NO HP");
        panelUtama.add(txt_noHp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        getContentPane().add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String ubahKeRupiah(int parm) {
        String mataUang = String.format(Locale.US, "%,d", parm);
        mataUang = mataUang.replaceAll(",",".");
        mataUang = "Rp " + mataUang;
        return mataUang;
    }
    
    void filterangka(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom No Hp/ID Hanya Bisa Memasukan Karakter Angka");
        }
    }
    
    private void cb_jenisTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_jenisTopUpActionPerformed
        // TODO add your handling code here:
        if (cb_jenisTopUp.getSelectedIndex() == 0) {
            tipe = "Tri";
            jLPilihPulsa.setVisible(true);
            jLPilihEMoney.setVisible(false);
            jLPilihGame.setVisible(false);
            btnHargaA.setText("Rp 10.000");
            btnHargaB.setText("Rp 25.000");
            btnHargaC.setText("Rp 50.000");
            btnHargaD.setText("Rp 100.000");
            pesanan = "PULSA";
        } else if (cb_jenisTopUp.getSelectedIndex() == 1) {
            tipe = "Dana";
            jLPilihPulsa.setVisible(false);
            jLPilihEMoney.setVisible(true);
            jLPilihGame.setVisible(false);
            btnHargaA.setText("Rp 20.000");
            btnHargaB.setText("Rp 30.000");
            btnHargaC.setText("Rp 50.000");
            btnHargaD.setText("Rp 100.000");
            pesanan = "E-MONEY";
        } else if (cb_jenisTopUp.getSelectedIndex() == 2) {
            tipe = "Mobile Legends";
            jLPilihPulsa.setVisible(false);
            jLPilihEMoney.setVisible(false);
            jLPilihGame.setVisible(true);
            btnHargaA.setText("86 Diamonds");
            btnHargaB.setText("172 Diamonds");
            btnHargaC.setText("257 Diamonds");
            btnHargaD.setText("429 Diamonds");
            pesanan = "GAME";
        }
    }//GEN-LAST:event_cb_jenisTopUpActionPerformed

    private void btn_pilihPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihPembayaranActionPerformed
        // TODO add your handling code here:
        if (tf_Nama.getText().equals("") || tf_noHp.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Anda belum mengisi nama atau nomer HP. Silahkan isi terlebih dahulu!", "Data Belum Lengkap", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tf_noHp.getText().length() < 10) {
            JOptionPane.showMessageDialog(this, "Nomer Hp minimal memiliki 10 digit.", "Data Belum Lengkap", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (diskonTotal.getText().equalsIgnoreCase("Rp 0.00")) {
            JOptionPane.showMessageDialog(this, "Data anda belum lengkap atau anda belum memilih nominal ataupun jenis top-up!. Silahkan isi terlebih dahulu!", "Anda belum memilih", JOptionPane.ERROR_MESSAGE);
            return;
        }
        metodePembayaran.setVisible(true);
    }//GEN-LAST:event_btn_pilihPembayaranActionPerformed

    private void btn_GoPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GoPayActionPerformed
        // TODO add your handling code here:
        tipe = "Go-Pay";
        btnHargaA.setText("Rp 10.000");
        btnHargaB.setText("Rp 20.000");
        btnHargaC.setText("Rp 50.000");
        btnHargaD.setText("Rp 100.000");
    }//GEN-LAST:event_btn_GoPayActionPerformed

    private void btn_ShopeePayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShopeePayActionPerformed
        // TODO add your handling code here:
        tipe = "Shopee-Pay";
        btnHargaA.setText("Rp 10.000");
        btnHargaB.setText("Rp 25.000");
        btnHargaC.setText("Rp 50.000");
        btnHargaD.setText("Rp 100.000");
    }//GEN-LAST:event_btn_ShopeePayActionPerformed

    private void btn_OvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OvoActionPerformed
        // TODO add your handling code here:
        tipe = "Ovo";
        btnHargaA.setText("Rp 15.000");
        btnHargaB.setText("Rp 20.000");
        btnHargaC.setText("Rp 50.000");
        btnHargaD.setText("Rp 100.000");
    }//GEN-LAST:event_btn_OvoActionPerformed

    private void btn_PUBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PUBGActionPerformed
        // TODO add your handling code here:
        tipe = "PUBG Mobile";
        btnHargaA.setText("50 + 3 UC");
        btnHargaB.setText("250 + 13 UC");
        btnHargaC.setText("500 + 25 UC");
        btnHargaD.setText("2500 + 375 UC");
        
    }//GEN-LAST:event_btn_PUBGActionPerformed

    private void btn_GenshinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenshinActionPerformed
        // TODO add your handling code here:
        tipe = "Genshin Impact";
        btnHargaA.setText("300 + 30 Genesis Cristal");
        btnHargaB.setText("980 + 110 Genesis Cristal");
        btnHargaC.setText("1.980 + 260 Genesis Cristal");
        btnHargaD.setText("6.480 + 1.600 Genesis Cristal");
    }//GEN-LAST:event_btn_GenshinActionPerformed

    private void btn_PunishingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PunishingActionPerformed
        // TODO add your handling code here:
        tipe = "Punishing Gray Raven";
        btnHargaA.setText("5 + 5 Rainbow Card");
        btnHargaB.setText("34 + 34 Rainbow Card");
        btnHargaC.setText("71 + 71 Rainbow Card");
        btnHargaD.setText("600 + 600 Rainbow Card");
    }//GEN-LAST:event_btn_PunishingActionPerformed

    private void btn_TriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TriActionPerformed
        // TODO add your handling code here:
        tipe = "Tri";
        btnHargaA.setText("Rp 10.000");
        btnHargaB.setText("Rp 25.000");
        btnHargaC.setText("Rp 50.000");
        btnHargaD.setText("Rp 100.000");
        
        
    }//GEN-LAST:event_btn_TriActionPerformed

    private void btn_TelkomselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TelkomselActionPerformed
        // TODO add your handling code here:
        tipe = "Telkomsel";
        btnHargaA.setText("Rp 10.000");
        btnHargaB.setText("Rp 25.000");
        btnHargaC.setText("Rp 50.000");
        btnHargaD.setText("Rp 100.000");
    }//GEN-LAST:event_btn_TelkomselActionPerformed

    private void btn_IndosatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IndosatActionPerformed
        // TODO add your handling code here:
        tipe = "Indosat";
        btnHargaA.setText("Rp 10.000");
        btnHargaB.setText("Rp 25.000");
        btnHargaC.setText("Rp 50.000");
        btnHargaD.setText("Rp 100.000");
    }//GEN-LAST:event_btn_IndosatActionPerformed

    private void btn_XlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XlActionPerformed
        // TODO add your handling code here:
        tipe = "XL";
        btnHargaA.setText("Rp 10.000");
        btnHargaB.setText("Rp 25.000");
        btnHargaC.setText("Rp 50.000");
        btnHargaD.setText("Rp 100.000");
    }//GEN-LAST:event_btn_XlActionPerformed

    private void btn_danaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_danaActionPerformed
        // TODO add your handling code here:
        tipe = "Dana";
        btnHargaA.setText("Rp 20.000");
        btnHargaB.setText("Rp 30.000");
        btnHargaC.setText("Rp 50.000");
        btnHargaD.setText("Rp 100.000");
    }//GEN-LAST:event_btn_danaActionPerformed

    private void btn_MLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MLActionPerformed
        // TODO add your handling code here:
        tipe = "Mobile Legends";
        btnHargaA.setText("86 Diamonds");
        btnHargaB.setText("172 Diamonds");
        btnHargaC.setText("257 Diamonds");
        btnHargaD.setText("429 Diamonds");
    }//GEN-LAST:event_btn_MLActionPerformed

    private void btnHargaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaAActionPerformed
        // TODO add your handling code here:
        if (tipe.equalsIgnoreCase("Tri")) {
            harga = 10000;
        }
        if (tipe.equalsIgnoreCase("Indosat")) {
            harga = 11000;
        }
        if (tipe.equalsIgnoreCase("XL")) {
            harga = 10000;
        }
        if (tipe.equalsIgnoreCase("Telkomsel")) {
            harga = 11500;
        }
        if (tipe.equalsIgnoreCase("Dana")) {
            harga = 25000;
        }
        if (tipe.equalsIgnoreCase("Go-Pay")) {
            harga = 10000;
        }
        if (tipe.equalsIgnoreCase("Shopee-Pay")) {
            harga = 10000;
        }
        if (tipe.equalsIgnoreCase("OVO")) {
            harga = 20000;
        }
        if (tipe.equalsIgnoreCase("Mobile Legends")) {
            harga = 17000;
        }
        if (tipe.equalsIgnoreCase("PUBG Mobile")) {
            harga = 10000;
        }
        if (tipe.equalsIgnoreCase("Genshin Impact")) {
            harga = 57000;
        }
        if (tipe.equalsIgnoreCase("Punishing Gray Raven")) {
            harga = 15000;
        }
        if (tf_noHp.getText().equals("")){
            return;
        }
        diskon = Double.parseDouble(tf_noHp.getText().substring(tf_noHp.getText().length() - 2)) / 10.0;
        nominalDiskon = (int)((diskon / 100.0) * 10000);
        diskonTotal.setText(ubahKeRupiah(nominalDiskon));
        total = harga - nominalDiskon;
        totalHarga.setText(ubahKeRupiah(total));
    }//GEN-LAST:event_btnHargaAActionPerformed

    private void btnHargaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaBActionPerformed
        // TODO add your handling code here:
        if (tipe.equalsIgnoreCase("Tri")) {
            harga = 25000;
        }
        if (tipe.equalsIgnoreCase("Indosat")) {
            harga = 26000;
        }
        if (tipe.equalsIgnoreCase("XL")) {
            harga = 25000;
        }
        if (tipe.equalsIgnoreCase("Telkomsel")) {
            harga = 27500;
        }
        if (tipe.equalsIgnoreCase("Dana")) {
            harga = 35000;
        }
        if (tipe.equalsIgnoreCase("Go-Pay")) {
            harga = 20000;
        }
        if (tipe.equalsIgnoreCase("Shopee-Pay")) {
            harga = 25000;
        }
        if (tipe.equalsIgnoreCase("OVO")) {
            harga = 25000;
        }
        if (tipe.equalsIgnoreCase("Mobile Legends")) {
            harga = 34000;
        }
        if (tipe.equalsIgnoreCase("PUBG Mobile")) {
            harga = 50000;
        }
        if (tipe.equalsIgnoreCase("Genshin Impact")) {
            harga = 172000;
        }
        if (tipe.equalsIgnoreCase("Punishing Gray Raven")) {
            harga = 82000;
        }
        if (tf_noHp.getText().equals("")){
            return;
        }
        diskon = Double.parseDouble(tf_noHp.getText().substring(tf_noHp.getText().length() - 2)) / 10.0;
        nominalDiskon = (int)((diskon / 100.0) * 10000);
        diskonTotal.setText(ubahKeRupiah(nominalDiskon));
        total = harga - nominalDiskon;
        totalHarga.setText(ubahKeRupiah(total));
    }//GEN-LAST:event_btnHargaBActionPerformed

    private void btnHargaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaCActionPerformed
        // TODO add your handling code here:
        if (tipe.equalsIgnoreCase("Tri")) {
            harga = 50000;
        }
        if (tipe.equalsIgnoreCase("Indosat")) {
            harga = 51000;
        }
        if (tipe.equalsIgnoreCase("XL")) {
            harga = 50000;
        }
        if (tipe.equalsIgnoreCase("Telkomsel")) {
            harga = 53500;
        }
        if (tipe.equalsIgnoreCase("Dana")) {
            harga = 55000;
        }
        if (tipe.equalsIgnoreCase("Go-Pay")) {
            harga = 50000;
        }
        if (tipe.equalsIgnoreCase("Shopee-Pay")) {
            harga = 50000;
        }
        if (tipe.equalsIgnoreCase("OVO")) {
            harga = 55000;
        }
        if (tipe.equalsIgnoreCase("Mobile Legends")) {
            harga = 50000;
        }
        if (tipe.equalsIgnoreCase("PUBG Mobile")) {
            harga = 100000;
        }
        if (tipe.equalsIgnoreCase("Genshin Impact")) {
            harga = 373000;
        }
        if (tipe.equalsIgnoreCase("Punishing Gray Raven")) {
            harga = 155000;
        }
        if (tf_noHp.getText().equals("")){
            return;
        }
        diskon = Double.parseDouble(tf_noHp.getText().substring(tf_noHp.getText().length() - 2)) / 10.0;
        nominalDiskon = (int)((diskon / 100.0) * 10000);
        diskonTotal.setText(ubahKeRupiah(nominalDiskon));
        total = harga - nominalDiskon;
        totalHarga.setText(ubahKeRupiah(total));
    }//GEN-LAST:event_btnHargaCActionPerformed

    private void btnHargaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaDActionPerformed
        // TODO add your handling code here:
        if (tipe.equalsIgnoreCase("Tri")) {
            harga = 100000;
        }
        if (tipe.equalsIgnoreCase("Indosat")) {
            harga = 101000;
        }
        if (tipe.equalsIgnoreCase("XL")) {
            harga = 100000;
        }
        if (tipe.equalsIgnoreCase("Telkomsel")) {
            harga = 104500;
        }
        if (tipe.equalsIgnoreCase("Dana")) {
            harga = 105000;
        }
        if (tipe.equalsIgnoreCase("Go-Pay")) {
            harga = 100000;
        }
        if (tipe.equalsIgnoreCase("Shopee-Pay")) {
            harga = 100000;
        }
        if (tipe.equalsIgnoreCase("OVO")) {
            harga = 105000;
        }
        if (tipe.equalsIgnoreCase("Mobile Legends")) {
            harga = 84000;
        }
        if (tipe.equalsIgnoreCase("PUBG Mobile")) {
            harga = 500000;
        }
        if (tipe.equalsIgnoreCase("Genshin Impact")) {
            harga = 1140000;
        }
        if (tipe.equalsIgnoreCase("Punishing Gray Raven")) {
            harga = 1235000;
        }
        if (tf_noHp.getText().equals("")){
            return;
        }
        diskon = Double.parseDouble(tf_noHp.getText().substring(tf_noHp.getText().length() - 2)) / 10.0;
        nominalDiskon = (int)((diskon / 100.0) * 10000);
        diskonTotal.setText(ubahKeRupiah(nominalDiskon));
        total = harga - nominalDiskon;
        totalHarga.setText(ubahKeRupiah(total));
    }//GEN-LAST:event_btnHargaDActionPerformed

    private void cb_metodePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_metodePembayaranActionPerformed
        // TODO add your handling code here:
        if (cb_metodePembayaran.getSelectedIndex() == 0) {
            cekMetodePembayaran = "Bank";
            jLTransferBank.setVisible(true);
            jLGerai.setVisible(false);
        } else if (cb_metodePembayaran.getSelectedIndex() == 1) {
            cekMetodePembayaran = "Gerai";
            jLTransferBank.setVisible(false);
            jLGerai.setVisible(true);
        }
    }//GEN-LAST:event_cb_metodePembayaranActionPerformed

    private void btn_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statusActionPerformed
        // TODO add your handling code here:
        if (status.equals("")) {
            JOptionPane.showMessageDialog(this, "Anda belum melakukan transaksi apapun.", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            JOptionPane.showMessageDialog(this, "Pembayaran dengan no VA atau kode pembayaran " + kode.getText() + " berhasil!, silahkan cek transaksi terakhir!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_statusActionPerformed

    private void btn_transaksiTerakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiTerakhirActionPerformed
        // TODO add your handling code here:
        if (status.equals("")) {
            JOptionPane.showMessageDialog(this, "Anda belum memiliki riwayat transaksi apapun.", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            this.dispose();
            new DetailPembayaran().setVisible(true);
        }
    }//GEN-LAST:event_btn_transaksiTerakhirActionPerformed

    private void bnt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_bayarActionPerformed
        // TODO add your handling code here:
        if (diskonTotal.getText().equalsIgnoreCase("Rp 0.00")) {
            JOptionPane.showMessageDialog(this, "Anda belum memesan apapun. Silahkan pesan terlebih dahulu!", "Anda belum memilih", JOptionPane.ERROR_MESSAGE);
            return;
        }
        txt_metodePembayaran.setText(pembayaran);
        if (cekMetodePembayaran.equalsIgnoreCase("Bank")) {
            txt_kodePembayaran.setText("(NO VA)");
            kode.setText(kodeTransferBank(tf_Nama.getText(), tf_noHp.getText()));
        } else if (cekMetodePembayaran.equalsIgnoreCase("Gerai")) {
            txt_kodePembayaran.setText("KODE PEMBAYARAN");
            kode.setText(kodeGerai(tf_Nama.getText(), tf_noHp.getText()));
        }
        metodePembayaran.setVisible(false);
        konfirmasiPembayaran.setVisible(true);
    }//GEN-LAST:event_bnt_bayarActionPerformed

    private void bcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaActionPerformed
        // TODO add your handling code here:
        pembayaran = "BANK BCA";
        
    }//GEN-LAST:event_bcaActionPerformed

    private void mandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandiriActionPerformed
        // TODO add your handling code here:
        pembayaran = "BANK MANDIRI";
    }//GEN-LAST:event_mandiriActionPerformed

    private void bniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bniActionPerformed
        // TODO add your handling code here:
        pembayaran = "BANK BNI";
    }//GEN-LAST:event_bniActionPerformed

    private void briActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_briActionPerformed
        // TODO add your handling code here:
        pembayaran = "BANK BRI";
    }//GEN-LAST:event_briActionPerformed

    private void alfamartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfamartActionPerformed
        // TODO add your handling code here:
        pembayaran = "ALFAMART";
    }//GEN-LAST:event_alfamartActionPerformed

    private void indomaretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indomaretActionPerformed
        // TODO add your handling code here:
        pembayaran = "INDOMARET";
    }//GEN-LAST:event_indomaretActionPerformed

    private void kantorPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kantorPosActionPerformed
        // TODO add your handling code here:
        pembayaran = "KANTOR POS";
    }//GEN-LAST:event_kantorPosActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        try {
                String sql = "INSERT INTO ordertopup VALUES ('" + tf_Nama.getText() +  "','" + tf_noHp.getText() + "','" + pesanan + "','" + harga + "','" + total + "','" + kode.getText() + "','" + total + "')";
                pstm = connection.prepareStatement(sql);
                ResultSet r = pstm.executeQuery();
                java.sql.Statement stm = connection.createStatement();
                pstm.execute();
                tf_Nama.setText("");
                tf_noHp.setText("");
                status = "Pesanan Berhasil";
                this.setVisible(true);
                konfirmasiPembayaran.setVisible(false);
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btn_okActionPerformed

    private void tf_noHpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_noHpKeyTyped
        filterangka(evt);
    }//GEN-LAST:event_tf_noHpKeyTyped

    public static String kodeTransferBank(String nama, String noHp) {
        StringBuilder kode = new StringBuilder();

        for (int i = 0; i < nama.length(); i++) {
            char namaChar = i < nama.length() ? nama.charAt(i) : ' ';
            char noHpChar = i < nama.length() ? noHp.charAt(i) : ' ';
            kode.append(namaChar).append(noHpChar);
        }
        kode.append(noHp.substring(nama.length()));
        return kode.toString().toUpperCase();
    }
    
    public static String kodeGerai(String nama, String noHp) {
        StringBuilder kode = new StringBuilder();

        for (int i = 0; i < nama.length(); i++) {
            char namaChar = i < nama.length() ? new StringBuilder(nama).reverse().toString().charAt(i) : ' ';
            char noHpChar = i < nama.length() ? noHp.charAt(i) : ' ';
            kode.append(namaChar).append(noHpChar);
        }
        kode.append(noHp.substring(nama.length()));
        return kode.toString().toUpperCase();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtamaTopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LP_Nominal;
    private javax.swing.JRadioButton alfamart;
    private javax.swing.JRadioButton bca;
    private javax.swing.JRadioButton bni;
    private javax.swing.JButton bnt_bayar;
    private javax.swing.JRadioButton bri;
    private javax.swing.ButtonGroup btGroup_MP;
    private javax.swing.JButton btnHargaA;
    private javax.swing.JButton btnHargaB;
    private javax.swing.JButton btnHargaC;
    private javax.swing.JButton btnHargaD;
    private javax.swing.JButton btn_Genshin;
    private javax.swing.JButton btn_GoPay;
    private javax.swing.JButton btn_Indosat;
    private javax.swing.JButton btn_ML;
    private javax.swing.JButton btn_Ovo;
    private javax.swing.JButton btn_PUBG;
    private javax.swing.JButton btn_Punishing;
    private javax.swing.JButton btn_ShopeePay;
    private javax.swing.JButton btn_Telkomsel;
    private javax.swing.JButton btn_Tri;
    private javax.swing.JButton btn_Xl;
    private javax.swing.JButton btn_dana;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_pilihPembayaran;
    private javax.swing.JButton btn_status;
    private javax.swing.JButton btn_transaksiTerakhir;
    private javax.swing.JComboBox<String> cb_jenisTopUp;
    private javax.swing.JComboBox<String> cb_metodePembayaran;
    private javax.swing.JLabel diskonTotal;
    private javax.swing.JRadioButton indomaret;
    private javax.swing.JLayeredPane jLGerai;
    private javax.swing.JLayeredPane jLPilihEMoney;
    private javax.swing.JLayeredPane jLPilihGame;
    private javax.swing.JLayeredPane jLPilihPulsa;
    private javax.swing.JLayeredPane jLTransferBank;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton kantorPos;
    private javax.swing.JLabel kode;
    private javax.swing.JFrame konfirmasiPembayaran;
    private javax.swing.JRadioButton mandiri;
    private javax.swing.JFrame metodePembayaran;
    private javax.swing.JPanel panelEMoney;
    private javax.swing.JPanel panelGame;
    private javax.swing.JPanel panelKp;
    private javax.swing.JPanel panelMp;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPanel panel_kode;
    private javax.swing.JPanel panel_provider;
    private javax.swing.JTextField tf_Nama;
    private javax.swing.JTextField tf_noHp;
    private javax.swing.JLabel totalHarga;
    private javax.swing.JLabel txt_Nama;
    private javax.swing.JLabel txt_PilihNominal;
    private javax.swing.JLabel txt_diskon;
    private javax.swing.JLabel txt_kodePembayaran;
    private javax.swing.JLabel txt_metodePembayaran;
    private javax.swing.JLabel txt_noHp;
    private javax.swing.JLabel txt_noHp1;
    private javax.swing.JLabel txt_pilihMp;
    private javax.swing.JLabel txt_serbaTopUp;
    private javax.swing.JLabel txt_topUpApa;
    private javax.swing.JLabel txt_total;
    // End of variables declaration//GEN-END:variables
}
