
import java.sql.Connection;
import javax.swing.JFrame;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Safiyyah Yahya
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form SerbaTopUP_1402023065
     */
    public Register() {
        initComponents();
        koneksi();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    public Connection connection;
    public Statement statement;
    public PreparedStatement pstm;
    public ResultSet rs = null;
       
    public void koneksi(){
        if(connection == null){
            try{
                String url = "jdbc:mysql://localhost:3306/serbatopup";                
                Class.forName("com.mysql.cj.jdbc.Driver");
                connection = DriverManager.getConnection(url, "root", "");
                java.sql.Statement st = connection.createStatement();
                //JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
            } catch(ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Koneksi Gagal");
                e.printStackTrace();
            }
        }        
    }
    
    public void setKosong(){
        tf_Username.setText("");
        tf_Password.setText("");        
        tf_RePassword.setText("");
    }
    
    private boolean usernameDiambil(String username) {
        try {
            String sql = "SELECT * FROM register WHERE username = ?";
            pstm = connection.prepareStatement(sql);
            pstm.setString(1, username);
            ResultSet r = pstm.executeQuery();
            return r.next();
        } catch (SQLException e) {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelRegister = new javax.swing.JPanel();
        txt_Register = new javax.swing.JLabel();
        txt_Username = new javax.swing.JLabel();
        tf_Username = new javax.swing.JTextField();
        txt_Password = new javax.swing.JLabel();
        tf_Password = new javax.swing.JPasswordField();
        tf_RePassword = new javax.swing.JPasswordField();
        check_showPassword = new javax.swing.JCheckBox();
        btn_register = new javax.swing.JButton();
        txt_RePassword = new javax.swing.JLabel();
        txt_readyAcc = new javax.swing.JLabel();
        txt_LoginHere = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(204, 204, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(722, 615));
        mainPanel.setMinimumSize(new java.awt.Dimension(722, 615));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegister.setBackground(new java.awt.Color(153, 153, 255));
        panelRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Register.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Register.setText("R E G I S T E R");
        panelRegister.add(txt_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, -1));

        txt_Username.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        txt_Username.setText("Username");
        panelRegister.add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 85, -1, -1));

        tf_Username.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        tf_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_UsernameActionPerformed(evt);
            }
        });
        panelRegister.add(tf_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 40));

        txt_Password.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        txt_Password.setText("Password");
        panelRegister.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        tf_Password.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        panelRegister.add(tf_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 340, 40));

        tf_RePassword.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        panelRegister.add(tf_RePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 340, 40));

        check_showPassword.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        check_showPassword.setText(" Show Password");
        check_showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_showPasswordActionPerformed(evt);
            }
        });
        panelRegister.add(check_showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        btn_register.setBackground(new java.awt.Color(204, 204, 255));
        btn_register.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_register.setText("REGISTER");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        panelRegister.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 150, -1));

        txt_RePassword.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        txt_RePassword.setText("Re-Password");
        panelRegister.add(txt_RePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        mainPanel.add(panelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 380, 460));

        txt_readyAcc.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        txt_readyAcc.setText("Already have an account?");
        mainPanel.add(txt_readyAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, -1, -1));

        txt_LoginHere.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        txt_LoginHere.setText("Login Here");
        txt_LoginHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_LoginHereMouseClicked(evt);
            }
        });
        mainPanel.add(txt_LoginHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_showPasswordActionPerformed
        if(check_showPassword.isSelected()){
            tf_Password.setEchoChar((char)0);
            tf_RePassword.setEchoChar((char)0);
        }else{
            tf_Password.setEchoChar('*');
            tf_RePassword.setEchoChar('*');
        }
    }//GEN-LAST:event_check_showPasswordActionPerformed
   
    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        String username_user, password, rePassword, query;        
        String url = "jdbc:mysql://localhost:3306/serbatopup";       
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection(url, "root", "");
            java.sql.Statement st = con.createStatement();
            
            if (tf_Username.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Username belum diisi", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
            }else if (usernameDiambil(tf_Username.getText())) {
                JOptionPane.showMessageDialog(this, "Username ini sudah digunakan", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
            } else if (new String(tf_Password.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(this, "Password belum diisi", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
            }else if (new String(tf_Password.getPassword()).length() < 8) {
                JOptionPane.showMessageDialog(this, "Panjang password minimal harus 8 karakter", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
            }else if (new String(tf_RePassword.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(this, "Tuliskan kembali password mu", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
            } else if (!(new String(tf_Password.getPassword()).equals(new String(tf_RePassword.getPassword())))){
                JOptionPane.showMessageDialog(this, "Password yang kamu masukkan tidak sesuai", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
             } else {
                username_user = tf_Username.getText();
                password = new String(tf_Password.getPassword());
                rePassword = new String(tf_RePassword.getPassword());
                query = "INSERT INTO register(username, password, rePassword) VALUES('" + username_user + "','" + password + "','" + rePassword + "')";
                st.execute(query);
                JOptionPane.showMessageDialog(null, "Berhasil registrasi", "Pesan Informasi", JOptionPane.INFORMATION_MESSAGE);
                setKosong();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal!", "Pesan Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void tf_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_UsernameActionPerformed

    private void txt_LoginHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_LoginHereMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txt_LoginHereMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JCheckBox check_showPassword;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JPasswordField tf_Password;
    private javax.swing.JPasswordField tf_RePassword;
    private javax.swing.JTextField tf_Username;
    private javax.swing.JLabel txt_LoginHere;
    private javax.swing.JLabel txt_Password;
    private javax.swing.JLabel txt_RePassword;
    private javax.swing.JLabel txt_Register;
    private javax.swing.JLabel txt_Username;
    private javax.swing.JLabel txt_readyAcc;
    // End of variables declaration//GEN-END:variables
}
